name: Competition
description: Publish a competition to the website
labels: ["type:competition"]
body:
  - type: dropdown
    id: lang
    attributes:
      label: Language
      options: [fr, en]
      default: 0
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true
  - type: input
    id: startDate
    attributes:
      label: Start date (YYYY-MM-DD)
    validations:
      required: true
  - type: input
    id: endDate
    attributes:
      label: End date (YYYY-MM-DD)
  - type: input
    id: location
    attributes:
      label: Location
  - type: input
    id: cover
    attributes:
      label: Cover image filename or static path (optional)
      description: Prefer a bundle-local filename next to index.md (e.g., cover.jpg). Static paths also work (e.g., images/competitions/xxx.jpg).
      placeholder: cover.jpg
  - type: textarea
    id: summary
    attributes:
      label: Summary (short)
  - type: input
    id: gallery
    attributes:
      label: Gallery images (comma separated, optional)
      description: Prefer bundle-local filenames next to index.md (e.g., gallery-1.jpg, gallery-2.jpg)
      placeholder: gallery-1.jpg, gallery-2.jpg
  - type: textarea
    id: content
    attributes:
      label: Description (Markdown)
      render: markdown
      description: Main content of the competition page
    validations:
      required: true
