name: News
description: Publish a news item to the website
labels: ["type:news"]
body:
  - type: dropdown
    id: lang
    attributes:
      label: Language
      description: Select the language for this news item
      options:
        - fr
        - en
      default: 0
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: e.g. Match result vs XYZ
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary (short)
      placeholder: One or two sentences
  - type: input
    id: cover
    attributes:
      label: Cover image filename or static path (optional)
      description: Prefer a bundle-local filename next to index.md (e.g., cover.jpg). Static paths also work (e.g., images/news/xxx.jpg).
      placeholder: cover.jpg
  - type: input
    id: tags
    attributes:
      label: Tags (comma separated)
      placeholder: e.g. match,senior,men
  - type: input
    id: categories
    attributes:
      label: Categories (comma separated)
      placeholder: e.g. results
  - type: input
    id: gallery
    attributes:
      label: Gallery images (comma separated, optional)
      description: Prefer bundle-local filenames next to index.md (e.g., gallery-1.jpg, gallery-2.jpg)
      placeholder: gallery-1.jpg, gallery-2.jpg
  - type: textarea
    id: content
    attributes:
      label: Content (Markdown)
      description: Main content of the article in Markdown
      render: markdown
    validations:
      required: true
