name: Publish from Issues

on:
  issues:
    types: [opened, edited, labeled, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Ensure labels exist
        uses: actions/github-script@v7
        with:
          script: |
            const toEnsure = [
              { name: 'type:news', color: '0366d6', description: 'Website: News item' },
              { name: 'type:competition', color: '0e8a16', description: 'Website: Competition' },
              { name: 'type:player', color: 'b60205', description: 'Website: Player' },
              { name: 'type:post', color: '1d76db', description: 'Website: Blog Post' },
              { name: 'type:gallery', color: 'fbca04', description: 'Website: Gallery Item' },
              { name: 'lang:fr', color: '5319e7', description: 'French content' },
              { name: 'lang:en', color: 'e99695', description: 'English content' },
            ];
            for (const l of toEnsure) {
              try {
                await github.rest.issues.getLabel({ owner: context.repo.owner, repo: context.repo.repo, name: l.name });
              } catch (e) {
                await github.rest.issues.createLabel({ owner: context.repo.owner, repo: context.repo.repo, name: l.name, color: l.color, description: l.description });
              }
            }

      - name: Add lang label based on form
        if: contains(github.event.issue.labels.*.name, 'type:news') || contains(github.event.issue.labels.*.name, 'type:competition') || contains(github.event.issue.labels.*.name, 'type:player') || contains(github.event.issue.labels.*.name, 'type:post') || contains(github.event.issue.labels.*.name, 'type:gallery')
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || '';
            const m = body.match(/^###\s+Language\n([\s\S]*?)(?:\n### |$)/mi);
            const lang = (m && m[1] || '').trim().toLowerCase();
            if (lang === 'fr' || lang === 'en') {
              await github.rest.issues.addLabels({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.issue.number, labels: [`lang:${lang}`] });
            }

      - name: Install script deps
        run: |
          echo "No deps"

      - name: Generate content from issue
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          node scripts/issue-to-content.mjs

      - name: Commit and push changes to feature branch
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          set -e
          BRANCH="content/issue-${ISSUE_NUMBER}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin
          if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
            echo "Remote branch exists; checking out origin/$BRANCH"
            git checkout -B "$BRANCH" "origin/$BRANCH"
          else
            echo "Creating new branch from origin/main -> $BRANCH"
            git checkout -B "$BRANCH" origin/main
          fi
          git add content/**
          if git diff --cached --quiet; then
            echo "No content changes"; exit 0;
          fi
          git commit -m "chore(content): generate from #${ISSUE_NUMBER}"
          git push -u origin "$BRANCH"

      - name: Open or update Pull Request
        if: ${{ !cancelled() }}
        uses: actions/github-script@v7
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        with:
          script: |
            const issue_number = parseInt(process.env.ISSUE_NUMBER, 10);
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = `content/issue-${issue_number}`;
            // Try to find an open PR from this branch
            const prs = await github.rest.pulls.list({ owner, repo, state: 'open', head: `${owner}:${branch}` });
            if (prs.data.length > 0) {
              const pr = prs.data[0];
              core.info(`PR already exists: #${pr.number}`);
              // Optionally update the title/body to ensure close keyword is present
              const title = pr.title || `content: generate from #${issue_number}`;
              const body = (pr.body || '').includes(`#${issue_number}`) ? pr.body : `${pr.body ? pr.body + '\n\n' : ''}Closes #${issue_number}`;
              await github.rest.pulls.update({ owner, repo, pull_number: pr.number, title, body });
            } else {
              const title = `content: generate from #${issue_number}`;
              const body = `Closes #${issue_number}`;
              const created = await github.rest.pulls.create({ owner, repo, title, head: branch, base: 'main', body });
              core.info(`Opened PR #${created.data.number}`);
            }
